<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FoodieHubDataSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed Categories
        $categories = [
            ['id' => 1, 'category_name' => 'Fast Food', 'category_slug' => 'fast-food', 'category_status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'category_name' => 'Desi Tadka', 'category_slug' => 'desi-tadka', 'category_status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'category_name' => 'Chill Drinks', 'category_slug' => 'chill-drinks', 'category_status' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'category_name' => 'Sweet Cravings', 'category_slug' => 'sweet-cravings', 'category_status' => 1, 'created_at' => now(), 'updated_at' => now()],
        ];

        foreach ($categories as $cat) {
            DB::table('food_Category')->updateOrInsert(['id' => $cat['id']], $cat);
        }

        // 2. Seed Food Items
        $foodItems = [
            [
                'id' => 1,
                'category_id' => 2,
                'food_name' => 'Chole Masala',
                'food_subtitle' => 'Punjabi Delight, Packed with Bold Spices',
                'food_slug' => 'chole-masala',
                'food_desc' => 'Protein-rich soya chunks cooked in spicy gravy',
                'food_image' => 'assets/images/1776666320_chole_img.jpg',
                'food_type' => '0',
                'food_stock' => 20,
                'food_price' => 1.00,
                'food_old_price' => 89.00,
                'food_rating' => 4.0,
                'food_preparation_time' => '30',
                'food_is_popular' => 1,
                'food_category' => 1,
                'food_is_featured' => 1,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'category_id' => 3,
                'food_name' => 'Mint Mojito',
                'food_subtitle' => 'Refreshing mint drink with lime and soda fizz',
                'food_slug' => 'mint-mojito',
                'food_desc' => 'Mint Mojito is a refreshing and cooling drink made with fresh mint leaves, zesty lime, and a hint of sweetness, all mixed with chilled soda. Bursting with crisp and tangy flavors, it’s the perfect thirst-quencher to beat the heat and refresh your senses with every sip.',
                'food_image' => 'assets/images/1776666813_mojito.jfif',
                'food_type' => '2',
                'food_stock' => 10,
                'food_price' => 99.00,
                'food_old_price' => 139.00,
                'food_rating' => 4.8,
                'food_preparation_time' => '10',
                'food_is_popular' => 1,
                'food_category' => 2,
                'food_is_featured' => 0,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'food_name' => 'Sandwich',
                'food_subtitle' => 'Fresh sandwich stuffed with cheesy fillings',
                'food_slug' => 'sandwich',
                'food_desc' => 'A delicious fresh sandwich loaded with rich, melty cheese and flavorful fillings, layered between soft, toasted bread. Perfectly balanced with a crispy bite and creamy texture, it’s a quick and satisfying snack for any time of the day.',
                'food_image' => 'assets/images/1776681069_sandwitch_img.jfif',
                'food_type' => '0',
                'food_stock' => 17,
                'food_price' => 69.00,
                'food_old_price' => 80.00,
                'food_rating' => 4.6,
                'food_preparation_time' => '15',
                'food_is_popular' => 1,
                'food_category' => 0,
                'food_is_featured' => 1,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'category_id' => 4,
                'food_name' => 'Black Forest Cake',
                'food_subtitle' => 'Soft chocolate sponge layered with cream and cherries',
                'food_slug' => 'black-forest-cake',
                'food_desc' => '“Black Forest Cake is a classic dessert made with soft chocolate sponge layers, filled with fresh whipped cream and juicy cherries. Topped with chocolate shavings and more cream, this indulgent treat delivers the perfect balance of sweetness, richness, and fruity freshness in every bite.',
                'food_image' => 'assets/images/1776673402_blackForest_cake.webp',
                'food_type' => '3',
                'food_stock' => 18,
                'food_price' => 300.00,
                'food_old_price' => 459.00,
                'food_rating' => 4.8,
                'food_preparation_time' => '50',
                'food_is_popular' => 1,
                'food_category' => 3,
                'food_is_featured' => 1,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'food_name' => 'Classic Veg Burger',
                'food_subtitle' => 'Quick Bites, Big Flavor',
                'food_slug' => 'classic-veg-burger',
                'food_desc' => 'Delicious and crispy fast food items perfect for satisfying your hunger instantly. From burgers to fries, enjoy every bite.',
                'food_image' => 'assets/images/1776709542_cheese_pizza.jfif',
                'food_type' => '0',
                'food_stock' => 3,
                'food_price' => 399.00,
                'food_old_price' => 499.00,
                'food_rating' => 4.7,
                'food_preparation_time' => '30',
                'food_is_popular' => 1,
                'food_category' => 0,
                'food_is_featured' => 0,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'food_name' => 'Chole Bhature',
                'food_subtitle' => 'A Flavor-Packed Punjabi Delight with Spicy Chole and Soft, Fluffy Bhature',
                'food_slug' => 'chole-bhature',
                'food_desc' => 'Chole Bhature is a classic North Indian dish that brings together spicy, tangy chickpea curry (chole) and soft, fluffy deep-fried bread (bhature). Bursting with bold flavors, aromatic spices, and a hint of tanginess, this dish is a true indulgence. Often served with pickled onions, green chutney, and a squeeze of lemon, Chole Bhature is a perfect blend of richness and comfort—ideal for a hearty meal any time of the day.',
                'food_image' => 'assets/images/1776709708_chole_bhature.jfif',
                'food_type' => '0',
                'food_stock' => 5,
                'food_price' => 70.00,
                'food_old_price' => 89.00,
                'food_rating' => 4.6,
                'food_preparation_time' => '15',
                'food_is_popular' => 1,
                'food_category' => 0,
                'food_is_featured' => 1,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'category_id' => 3,
                'food_name' => 'Lemon Iced Tea',
                'food_subtitle' => 'A Cool and Refreshing Citrus Drink Perfect for Beating the Heat with Every Sip',
                'food_slug' => 'lemon-iced-tea',
                'food_desc' => 'Lemon Iced Tea is a light, refreshing beverage made with freshly brewed tea, a splash of tangy lemon juice, and just the right amount of sweetness. Served chilled with ice cubes and often garnished with lemon slices or mint leaves, it delivers a perfect balance of citrusy zing and soothing tea flavor. Ideal for hot summer days, this drink not only refreshes your body but also uplifts your mood with its crisp and revitalizing taste.',
                'food_image' => 'assets/images/1776709900_lemon_tea.jfif',
                'food_type' => '2',
                'food_stock' => 11,
                'food_price' => 99.00,
                'food_old_price' => 119.00,
                'food_rating' => 4.2,
                'food_preparation_time' => '20',
                'food_is_popular' => 0,
                'food_category' => 2,
                'food_is_featured' => 0,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'category_id' => 4,
                'food_name' => 'Gulab Jamun',
                'food_subtitle' => 'Soft, Juicy Dessert Balls Soaked in Fragrant Sugar Syrup',
                'food_slug' => 'gulab-jmun',
                'food_desc' => 'Gulab Jamun is one of India’s most loved traditional desserts, made from soft dough balls that are deep-fried to a golden brown and then soaked in a rich, aromatic sugar syrup infused with cardamom and rose essence. Each bite is irresistibly soft, juicy, and sweet, delivering a melt-in-the-mouth experience. Often served warm and garnished with nuts like pistachios or almonds, Gulab Jamun is the perfect ending to any meal or celebration.',
                'food_image' => 'assets/images/1776710067_gulab_jamun.jpg',
                'food_type' => '3',
                'food_stock' => 28,
                'food_price' => 99.00,
                'food_old_price' => 119.00,
                'food_rating' => 4.8,
                'food_preparation_time' => '35',
                'food_is_popular' => 1,
                'food_category' => 3,
                'food_is_featured' => 1,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'category_id' => 3,
                'food_name' => 'Chocolate Milkshake',
                'food_subtitle' => 'Refreshing, Cool & Perfectly Chilled Beverages for Every Mood',
                'food_slug' => 'chocolate-milkshake',
                'food_desc' => 'Quench your thirst with refreshing drinks that energize your day and keep you cool. From fruity juices to creamy shakes and fizzy coolers, each sip is crafted to give you a refreshing and delightful experience.',
                'food_image' => 'assets/images/1776752215_chockolate_milk.jfif',
                'food_type' => '2',
                'food_stock' => 15,
                'food_price' => 89.00,
                'food_old_price' => 99.00,
                'food_rating' => 4.2,
                'food_preparation_time' => '20',
                'food_is_popular' => 0,
                'food_category' => 2,
                'food_is_featured' => 0,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'food_name' => 'Pani Puri',
                'food_subtitle' => 'Spicy, Tangy & Full of Desi Street-Style Flavors You’ll Love',
                'food_slug' => 'pani-puri',
                'food_desc' => 'Experience the vibrant taste of Indian streets with bold, spicy, and tangy snacks. These quick bites are full of flavor, crunch, and excitement, making them perfect for evening cravings and fun food moments.',
                'food_image' => 'assets/images/1776752727_pani_puri.jfif',
                'food_type' => '0',
                'food_stock' => 28,
                'food_price' => 50.00,
                'food_old_price' => 65.00,
                'food_rating' => 4.6,
                'food_preparation_time' => '10',
                'food_is_popular' => 1,
                'food_category' => 0,
                'food_is_featured' => 0,
                'food_status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($foodItems as $item) {
            DB::table('foodItems')->updateOrInsert(['id' => $item['id']], $item);
        }

        // 3. Seed Home Edit Pages (home, menu, about, contact)
        $homeContent = [
            'home_banner' => [
                'subtitle' => 'Fastest Food Delivery',
                'title1' => 'Be The Quickest',
                'title2' => 'In Your Food',
                'color_title' => 'Delivery',
                'desc' => 'From kitchen to your door — hot, fresh & lightning fast. Order your favorite meals anytime with FoodieHub.',
                'btn_text1' => 'Shop Now',
                'btn_url1' => '/cart',
                'btn_text2' => 'Explore Menu',
                'btn_url2' => '/menu',
                'banner_img' => null,
                'image' => 'uploads/WeyeEFn86AuREy8NXgrIuhsdCCSxp4ujirNwsGWO.png',
            ],
            'home_wcu' => [
                'home_wcu_title' => 'Experience the Best Food Service',
                'home_wcu_subtitle' => 'We deliver more than just food — we deliver experience',
                'items' => [
                    ['title' => 'Fast Delivery', 'desc' => 'Get your food delivered quickly and always fresh. We make sure your cravings are satisfied without delay.', 'icon' => 'Delivery'],
                    ['title' => 'Fresh Ingredients', 'desc' => 'We use only high-quality and fresh ingredients. Every dish is prepared with care and hygiene.', 'icon' => 'Fresh'],
                    ['title' => 'Easy Payment', 'desc' => 'We use only high-quality and fresh ingredients. Every dish is prepared with care and hygiene.', 'icon' => 'Payment'],
                    ['title' => 'Expert Chefs', 'desc' => 'Enjoy a smooth and secure checkout process. Multiple payment options for your convenience.', 'icon' => 'ExpertChefs'],
                ],
            ],
            'home_hiw' => [
                'home_hiw_subtitle' => 'Simple Process',
                'home_hiw_title' => 'How It Works',
                'home_hiw_desc' => 'From selecting your favorite dishes to fast doorstep delivery, FoodieHub makes ordering food simple, quick, and satisfying.',
                'home_hiw_btn_text' => 'Explore Menu',
                'home_hiw_btn_url' => '/menu',
                'items' => [
                    ['title' => 'Choose Your Food', 'desc' => 'Explore our delicious menu and pick your favorite meals, snacks, and drinks in just a few clicks.', 'icon' => 'Choose', 'step' => '01'],
                    ['title' => 'We Prepare It Fresh', 'desc' => 'Once you place your order, our kitchen starts preparing your food fresh with quality ingredients and care.', 'icon' => 'Fresh', 'step' => '02'],
                    ['title' => 'Fast Delivery', 'desc' => 'Our delivery team brings your order hot and fresh right to your doorstep in the shortest time possible.', 'icon' => 'fastDelivery', 'step' => '03'],
                ],
            ],
            'home_specialOffer' => [
                'home_offer_subtitle' => 'Limited Time Offer',
                'home_offer_title' => 'Get 30% Off On Your First Orde',
                'home_offer_desc' => 'Enjoy your favorite meals at a discounted price. Fresh, delicious, and delivered right to your doorstep.',
                'home_offer_btn_text' => 'Order Now',
                'home_offer_btn_url' => '/cart',
                'image' => 'uploads/qSi7v9BGz5zlvHZvdHjZALY4lLKXCVztN5xP0Bba.png',
            ],
            'home_testom' => [
                'home_testi_subtitle' => 'Testimonials',
                'home_testi_title' => 'Loved By Food Lovers',
                'items' => [
                    ['desc' => 'Absolutely loved the burger and fries. Delivery was super quick and food arrived hot.', 'rating' => '5', 'name' => 'Rahul Rajput', 'emotion' => 'This is Great..!!', 'image' => 'uploads/EuZStbRj0Ad60UsMI9mE5rrh7jEytE8KnBP3oud2.png'],
                    ['desc' => 'The pizza was cheesy, fresh, and full of flavor. One of the best online food experiences.', 'rating' => '4', 'name' => 'Mohit Sharma', 'emotion' => 'Dishes is literally Awsome..!!', 'image' => 'uploads/mUyVdtGfCScv9O754C3FwFCtS5SZR1t8FighIE9Q.png'],
                    ['desc' => 'FoodieHub made my dinner so easy. Great taste, great service, and smooth ordering process', 'rating' => '5', 'name' => 'Himanshu Singh', 'emotion' => 'Great taste ever i tasted..!!', 'image' => 'uploads/UUcK9xYEDgdySoqSee1RRuJPQXnR5G0Jg2QvVizp.png'],
                ],
            ],
            'home_faq' => [
                'home_faq_subtitle' => 'Help & Support',
                'home_faq_title' => 'Frequently Asked Questions',
                'home_faq_desc' => 'Got questions about delivery, payments, or food quality? We’ve answered the most common things here to make your ordering experience smooth and easy.',
                'home_faq_btn_text' => 'Contact Us',
                'home_faq_btn_link' => '/contact',
                'items' => [
                    ['question' => 'How long does delivery take?', 'answer' => 'We usually deliver your order within 25 to 35 minutes depending on your location, traffic, and order size.'],
                    ['question' => 'Do you offer cash on delivery?', 'answer' => 'Yes, we offer cash on delivery as well as secure online payment options for your convenience.'],
                    ['question' => 'Can I track my order in real time?', 'answer' => 'Yes, once your order is confirmed, you can track its delivery progress in real time.'],
                    ['question' => 'Are your ingredients fresh?', 'answer' => 'Absolutely. We use fresh and quality ingredients to prepare every order with care and great taste.'],
                    ['question' => 'Do you offer discounts or special deals?', 'answer' => 'Yes, we regularly offer combo deals, discounts, and limited-time food offers on selected menu items.'],
                ],
            ],
        ];

        $menuContent = [
            'menu_banner' => [
                'subtitle' => 'Fresh, hot & made with love',
                'title1' => 'Be The Quickest',
                'title2' => 'In Your Food',
                'color_title' => 'Delivery',
                'desc' => 'From cheesy pizzas to juicy burgers and refreshing drinks, discover a wide variety of Tasty dishes crafted just for you.',
                'btn_text1' => 'Shop Now',
                'btn_url1' => '/cart',
                'btn_text2' => 'Explore Menu',
                'btn_url2' => '/menu',
                'banner_img' => null,
                'image' => 'uploads/UH13aar8bdtTMOaRZiav0vW3HjrPeuBuN2ftvPMz.png',
            ],
        ];

        $aboutContent = [
            'about_banner' => [
                'subtitle' => 'Know More About Us',
                'title1' => 'We Deliver More',
                'title2' => 'Than Just',
                'color_title' => 'Food',
                'desc' => "At FoodieHub, we bring people together through great food. Fresh ingredients, fast delivery, and flavors you'll love — every time.",
                'btn_text1' => 'Order Now',
                'btn_url1' => '/cart',
                'btn_text2' => 'Contact Us',
                'btn_url2' => '/contact',
                'banner_img' => null,
                'image' => 'uploads/05YyYcXWa7xZzntQdH6NHoU2mi39xXBVMJbk7GI1.png',
            ],
            'About_Our_Story' => [
                'subtitle' => 'Our Story',
                'title' => 'Bringing Delicious Food To Your Doorstep',
                'desc1' => 'FoodieHub started with a simple idea — to make delicious, restaurant-quality food accessible to everyone. We believe food is not just about taste, it\'s about experience.',
                'desc2' => 'From fresh ingredients to fast delivery, our mission is to serve happiness in every bite. Whether it\'s fast food or traditional flavors, we’ve got something for everyone.',
                'btn_text' => 'Explore Menu',
                'btn_url' => '/menu',
            ],
            'about_our_story' => [
                'image' => 'uploads/3dZhoOqPVvExwV6vwtvcNk8GyjvxxKGiJG166iE0.png',
            ],
            'about_special' => [
                'subtitle' => 'What We Serve',
                'title' => 'Our Specialities',
                'desc' => 'From spicy desi meals to sweet desserts, FoodieHub brings all your favorite flavors together in one place.',
                'items' => [
                    ['box_title' => 'Fast Food', 'box_desc' => 'Crispy, cheesy, and loaded with flavor — perfect for your quick cravings.', 'image' => 'uploads/15UwySqlG5xcMgggmcQn0wSiJx0DTqMn8y6eP0Jp.webp'],
                    ['box_title' => 'Desi Tadka', 'box_desc' => 'Authentic Indian flavors made with rich spices and homely love.', 'image' => 'uploads/fWnPUf35WcoRUJtxigMDamp85Wmld4p4Oa61MX2C.jpg'],
                    ['box_title' => 'Chill Drinks', 'box_desc' => 'Refreshing beverages and cool sips to complete every meal.', 'image' => 'uploads/tOMfAyCaG89bMVcxXshQhkOjsTU2V7L1Q53AWxfI.jpg'],
                    ['box_title' => 'Sweet Cravings', 'box_desc' => 'Delightful desserts and sweets that make every ending perfect.', 'image' => 'uploads/kiYCvkq6rldIhFZ51hmhhpNoolLmv31F9H4NOKPN.jpg'],
                ],
            ],
            'aboutOffer' => [
                'subtitle' => 'Ready To Order?',
                'title' => 'Ready To Order?',
                'desc' => 'Fresh flavors, quick delivery, and your favorite dishes are waiting for you. Order now and enjoy the FoodieHub experience.',
                'btn_text1' => 'Order Now',
                'btn_url1' => '/cart',
                'btn_text2' => 'Explore Menu',
                'btn_url2' => '/menu',
            ],
        ];

        $contactContent = [
            'contact_banner' => [
                'subtitle' => 'Get In Touch',
                'title1' => "We'd Love To Hear",
                'title2' => 'From You',
                'color_title' => 'FoodieHub Support',
                'desc' => 'Have questions about your order, menu, or delivery? Our team is here to help you anytime.',
                'btn_text1' => 'Explore Menu',
                'btn_url1' => '/menu',
                'btn_text2' => 'Call Now',
                'btn_url2' => '/contact#contact-form',
                'banner_img' => null,
                'image' => 'uploads/fveCGTcVFSVIpAVe4sl9dRvC8medStck7tmF9W13.jpg',
            ],
            'contact_info' => [
                'items' => [
                    ['title' => 'Our Location', 'subtitle' => 'Our Location', 'icon' => 'location'],
                    ['title' => 'Call Us', 'subtitle' => 'Call Us', 'icon' => 'contact'],
                    ['title' => 'Email Us', 'subtitle' => 'Email Us', 'icon' => 'email'],
                    ['title' => 'Opening Hours', 'subtitle' => 'Opening Hours', 'icon' => 'timing'],
                ],
            ],
            'contact_form' => [
                'subtitle' => 'Contact Us',
                'title' => 'Let’s Start a',
                'color_title' => 'Conversation',
                'desc' => 'Got a question, food request, or feedback? We’re always ready to hear from you and help you out.',
                'point1' => 'Quick response from our team',
                'point2' => 'Easy support for orders & queries',
                'point3' => 'Friendly service with FoodieHub style',
                'btn_text' => 'Send Message',
                'btn_url' => '#',
            ],
            'contact_visit' => [
                'subtitle' => 'Visit Us',
                'title' => 'Come & Enjoy Food With Us',
                'desc' => 'Stop by our place for fresh flavors, quick service, and a warm FoodieHub experience.',
                'locationTitle' => 'Location',
                'locationSubtitle' => 'Phase 7 Mohali , Chandigarh',
                'timingTitle' => 'Opening Hours',
                'timingSubtitle' => '10:00 AM - 11:00 PM',
                'contactTitle' => 'Contact',
                'contactSubtitle' => '+91 6284229435',
                'btn_text' => 'Get Directions',
                'btn_url' => '#',
            ],
        ];

        DB::table('home_edit')->updateOrInsert(['pages' => 'home'], ['content' => json_encode($homeContent)]);
        DB::table('home_edit')->updateOrInsert(['pages' => 'menu'], ['content' => json_encode($menuContent)]);
        DB::table('home_edit')->updateOrInsert(['pages' => 'about'], ['content' => json_encode($aboutContent)]);
        DB::table('home_edit')->updateOrInsert(['pages' => 'contact'], ['content' => json_encode($contactContent)]);
    }
}
